//
//  TabBarProtocols.swift
//  Express24
//
//  Created by Ibrokhim Movlonov on 23/05/22.
//  Copyright © 2022 newmax. All rights reserved.
//
//  Template generated by Ibrokhim Movlonov

import Foundation

// MARK: - ViewController
protocol TabBarPresenterOutput: AnyObject {
    
}

// MARK: - Interactable
protocol TabBarInteractable: AnyObject {
    
}

// MARK: - Presentable
protocol TabBarPresentable: AnyObject {

}

// MARK: - Routing
protocol TabBarRouting: AnyObject {

}
