//
//  TabBarConfigurator.swift
//  Express24
//
//  Created by Ibrokhim Movlonov on 23/05/22.
//  Copyright © 2022 newmax. All rights reserved.
//
//  Template generated by Ibrokhim Movlonov

import UIKit

class TabBarConfigurator {
    
    static func configureModule() -> TabBarViewController {
        let viewController = TabBarViewController()
        let router = TabBarRouter()
        let interactor = TabBarInteractor()
        let presenter = TabBarPresenter()
        
        viewController.interactor = interactor
        interactor.presenter = presenter
        interactor.router = router
        presenter.viewController = viewController
        router.viewController = viewController
        
        return viewController
    }
}
