//
//  TabBarInteractor.swift
//  Express24
//
//  Created by Ibrokhim Movlonov on 23/05/22.
//  Copyright © 2022 newmax. All rights reserved.
//
//  Template generated by Ibrokhim Movlonov

import UIKit

class TabBarInteractor {
    
    // MARK: - Properties
    var presenter: TabBarPresentable?
    var router: TabBarRouting?
    
}

// MARK: - TabBarInteractable
extension TabBarInteractor: TabBarInteractable {
    
}
