//
//  TabBarRouter.swift
//  Express24
//
//  Created by Ibrokhim Movlonov on 23/05/22.
//  Copyright © 2022 newmax. All rights reserved.
//
//  Template generated by Ibrokhim Movlonov

import UIKit

class TabBarRouter {
    
    // MARK: - Properties
    weak var viewController: TabBarViewController?
    
}

// MARK: - TabBarRouting
extension TabBarRouter: TabBarRouting {
    
}
